#!/usr/bin/env python3
"""Build the "additional telemetry tables" appendix of docs/FIELDS.md from the JSON
produced by scripts/collect_telemetry_columns.py.

Offline -- no DB needed. Reads telemetry_appendix_columns.json, formats a reference
appendix (an index, then one compact Field|Type|Example table per telemetry table),
and splices it into docs/FIELDS.md between marker comments. Idempotent: rerun after
refreshing the JSON to update the appendix in place.

Usage:
    python3 scripts/build_telemetry_appendix.py [path/to/telemetry_appendix_columns.json]
"""
import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
_DEFAULT = ROOT / "data" / "telemetry_appendix_columns.json"
if not _DEFAULT.exists():
    _DEFAULT = ROOT / "telemetry_appendix_columns.json"   # fall back to repo root
JSON_PATH = Path(sys.argv[1]) if len(sys.argv) > 1 else _DEFAULT
FIELDS = ROOT / "docs" / "FIELDS.md"

BEGIN = "<!-- BEGIN telemetry appendix (generated by scripts/build_telemetry_appendix.py) -->"
END = "<!-- END telemetry appendix -->"

# Tables already covered (with descriptions) in the main glossary body -- skip here.
ALREADY_DOCUMENTED = {
    "guider_centroids", "environmentmonitor_telescope",
    "environmentmonitor_tower", "environmentmonitor_dust",
}


def esc(s):
    return str(s).replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def example_cell(v):
    return "" if v in (None, "", "None") else esc(v)


data = json.load(open(JSON_PATH))
ok = [r for r in data if not r["error"] and r["tablename"] not in ALREADY_DOCUMENTED]
skipped = [r for r in data if not r["error"] and r["tablename"] in ALREADY_DOCUMENTED]
bad = [r for r in data if r["error"]]

collected = dt.date.fromtimestamp(JSON_PATH.stat().st_mtime).isoformat()
ncols_total = sum(r["ncols"] for r in ok)

out = [BEGIN, "", "## Appendix: additional telemetry tables", ""]
out.append(
    "The main glossary above covers only the telemetry tables `telemetry_mining` "
    "integrates directly. This appendix is a broader **reference listing of column names** "
    "for other `telemetry`-schema tables that may be useful in future studies. It is "
    "deliberately **not hand-annotated** -- a column's name, its SQL type, and one sampled "
    "value are usually enough to tell what the quantity is."
)
out.append("")
out.append(
    "It is generated, not hand-typed: `scripts/collect_telemetry_columns.py` lists the "
    "columns via `information_schema` against the live DB (see the \"explore a telemetry "
    "table\" note near the top of this file), and `scripts/build_telemetry_appendix.py` "
    "formats them here. To refresh or extend it, edit the table list in the collector, "
    "rerun it where the DB is reachable, and rerun the builder."
)
out.append("")
out.append(
    "Reach any column the same way as the integrated telemetry tables: "
    "`exp.telemetry('<table>', columns=['<col>'])` for the rows within an exposure's time "
    "window, or `telemetry_mining.db.fetch_df(Config.default(), \"SELECT ... FROM "
    "telemetry.<table> ...\")` for an arbitrary query."
)
out.append("")
out.append(
    f"*{len(ok)} tables, {ncols_total} columns (DB snapshot {collected}). Example values "
    "are from a single sampled row; a blank means that column was NULL in the sampled row.*"
)
if skipped:
    names = ", ".join(f"`{r['tablename']}`" for r in skipped)
    out.append("")
    out.append(f"Omitted here because they are already documented in full above: {names}.")
out.append("")

# --- index ------------------------------------------------------------------
out.append("| Telemetry variable | Table | Columns |")
out.append("|---|---|---|")
for r in ok:
    label = f"`{r['shared_variable']}`" if r["shared_variable"] else ""
    out.append(f"| {label} | [`{r['tablename']}`](#{r['tablename']}) | {r['ncols']} |")
out.append("")

# --- per-table tables -------------------------------------------------------
for r in ok:
    out.append(f"### {r['tablename']}")
    out.append("")
    if r["shared_variable"]:
        out.append(f"Shared variable `{r['shared_variable']}`.")
        out.append("")
    out.append("| Field | Type | Example |")
    out.append("|---|---|---|")
    # alphabetical (case-insensitive) by column name -- easier to find a field
    for name, dtype, example in sorted(r["columns"], key=lambda c: str(c[0]).lower()):
        out.append(f"| {esc(name)} | {esc(dtype)} | {example_cell(example)} |")
    out.append("")

# --- tables that don't exist ------------------------------------------------
if bad:
    out.append("### Requested tables not found in this snapshot")
    out.append("")
    out.append(
        "These were in the collection list but returned no columns -- they don't exist in "
        "the `telemetry` schema as named (e.g. per-GFA-camera `guideN`/`focusN` tables, or "
        "renamed/retired tables):"
    )
    out.append("")
    out.append(", ".join(f"`{r['tablename']}`" for r in bad))
    out.append("")

out.append(END)
appendix = "\n".join(out)

text = FIELDS.read_text()
if BEGIN in text:
    text = text[: text.index(BEGIN)].rstrip() + "\n\n" + appendix + "\n"
else:
    text = text.rstrip() + "\n\n" + appendix + "\n"
FIELDS.write_text(text)

print(f"Spliced appendix into {FIELDS.relative_to(ROOT)}")
print(f"  {len(ok)} tables, {ncols_total} columns; "
      f"{len(skipped)} already-documented skipped; {len(bad)} not found.")
